// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.Infrastructure.Persistence;

#nullable disable

namespace Pos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20261003075952_InstalledLicenses")]
    partial class InstalledLicenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Pos.Domain.Audit.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorizedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizedBy")
                        .HasDatabaseName("IX_AuditEntries_AuthorizedBy");

                    b.HasIndex("Action", "CreatedAt")
                        .HasDatabaseName("IX_AuditEntries_Action_CreatedAt");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("IX_AuditEntries_CreatedAt");

                    b.HasIndex("CreatedBy", "CreatedAt")
                        .HasDatabaseName("IX_AuditEntries_CreatedBy");

                    b.HasIndex("EntityType", "CreatedAt")
                        .HasDatabaseName("IX_AuditEntries_EntityType_CreatedAt");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditEntries_Entity");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Business.BusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterMessage")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BusinessProfile", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.CashShifts.CashMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AuthorizedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CashShiftId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CashShiftId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_CashMovements_Shift_Sequence");

                    b.ToTable("CashMovements", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.CashShifts.CashShift", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CancelledCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CardCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CashCancelledCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CashRefundsCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CashSalesCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosingComment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CountedCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreditNotesIssuedCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CustomerPaymentVoidsCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CustomerPaymentVoidsNonCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CustomerPaymentsCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CustomerPaymentsNonCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DepositsCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DifferenceCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExpectedCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NonCashRefundsCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OnAccountSalesCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OpenedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpeningFloatCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SalesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TotalSoldCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TransferCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("WithdrawalsCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("IX_CashShifts_Number");

                    b.HasIndex("RegisterCode")
                        .IsUnique()
                        .HasDatabaseName("IX_CashShifts_OpenPerRegister")
                        .HasFilter("\"Status\" = 'OPEN'");

                    b.HasIndex("OpenedAt", "Id")
                        .HasDatabaseName("IX_CashShifts_OpenedAt");

                    b.HasIndex("OpenedBy", "OpenedAt")
                        .HasDatabaseName("IX_CashShifts_OpenedBy_OpenedAt");

                    b.ToTable("CashShifts", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.CashShifts.ShiftCut", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorizedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("CancelledCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CardCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CashCancelledCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CashRefundsCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CashSalesCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CountedCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreditNotesIssuedCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerPaymentVoidsCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerPaymentVoidsNonCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerPaymentsCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerPaymentsNonCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DepositsCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DifferenceCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpectedCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GeneratedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("NonCashRefundsCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OnAccountSalesCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OpeningFloatCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SalesCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ShiftNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ShiftOpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftOpenedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSoldCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TransferCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("WithdrawalsCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt", "Id")
                        .HasDatabaseName("IX_ShiftCuts_GeneratedAt");

                    b.HasIndex("GeneratedBy", "GeneratedAt")
                        .HasDatabaseName("IX_ShiftCuts_GeneratedBy_GeneratedAt");

                    b.HasIndex("Type", "Number")
                        .IsUnique()
                        .HasDatabaseName("IX_ShiftCuts_Type_Number");

                    b.HasIndex(new[] { "ShiftId" }, "IX_ShiftCuts_ClosingPerShift")
                        .IsUnique()
                        .HasFilter("\"Type\" = 'Z'");

                    b.HasIndex(new[] { "ShiftId" }, "IX_ShiftCuts_ShiftId");

                    b.ToTable("ShiftCuts", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_NameKey")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("IsActive", "NameKey")
                        .HasDatabaseName("IX_Categories_IsActive_NameKey")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.CreditNotes.CreditNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("InitialCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SaleReturnId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("IX_CreditNotes_Number");

                    b.HasIndex("SaleReturnId")
                        .HasDatabaseName("IX_CreditNotes_SaleReturnId");

                    b.ToTable("CreditNotes", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.CreditNotes.CreditNoteMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreditNoteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SaleReturnId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreditNoteId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_CreditNoteMovements_Note_Sequence");

                    b.ToTable("CreditNoteMovements", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreditLimitCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreditMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_TaxId")
                        .HasFilter("\"TaxId\" IS NOT NULL");

                    b.HasIndex("IsActive", "SearchText")
                        .HasDatabaseName("IX_Customers_Active_Search");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Discounts.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsesCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Coupons_Code");

                    b.ToTable("Coupons", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Discounts.DiscountApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("ApprovedBasisPoints")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AuthorizedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DraftId", "RequestedBy")
                        .HasDatabaseName("IX_DiscountApprovals_Draft");

                    b.ToTable("DiscountApprovals", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Inventory.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityThousandths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Quantity");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("ResultingStockThousandths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ResultingStock");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("IX_InventoryMovements_CreatedAt");

                    b.HasIndex("ProductId", "CreatedAt")
                        .HasDatabaseName("IX_InventoryMovements_Product_CreatedAt");

                    b.HasIndex("ProductId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_InventoryMovements_Product_Sequence");

                    b.HasIndex("Type", "CreatedAt")
                        .HasDatabaseName("IX_InventoryMovements_Type_CreatedAt");

                    b.ToTable("InventoryMovements", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Inventory.ProductStock", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovementCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OnHandThousandths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OnHand");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("ProductStocks", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Inventory.StockAlertAcknowledgement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LocalDate", "Level", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_StockAlertAcknowledgements_User_Date_Level_Product");

                    b.ToTable("StockAlertAcknowledgements", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCritical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<long?>("MinimumStockThousandths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MinimumStock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSearch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PriceCents");

                    b.Property<long?>("ReorderPointThousandths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReorderPoint");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TracksInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("H87");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Barcode")
                        .HasFilter("\"DeletedAt\" IS NULL AND \"Barcode\" IS NOT NULL");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Products_CategoryId")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Sku")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("UnitCode");

                    b.HasIndex("NameSearch", "Sku")
                        .HasDatabaseName("IX_Products_NameSearch")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("TracksInventory", "IsActive")
                        .HasDatabaseName("IX_Products_TracksInventory")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Products.ProductImage", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Products.UnitOfMeasure", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("DecimalPlaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("UnitsOfMeasure", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "H87",
                            DecimalPlaces = 0,
                            Name = "Pieza",
                            SortOrder = 1
                        },
                        new
                        {
                            Code = "KGM",
                            DecimalPlaces = 3,
                            Name = "Kilogramo",
                            SortOrder = 2
                        },
                        new
                        {
                            Code = "GRM",
                            DecimalPlaces = 0,
                            Name = "Gramo",
                            SortOrder = 3
                        },
                        new
                        {
                            Code = "LTR",
                            DecimalPlaces = 3,
                            Name = "Litro",
                            SortOrder = 4
                        },
                        new
                        {
                            Code = "MLT",
                            DecimalPlaces = 0,
                            Name = "Mililitro",
                            SortOrder = 5
                        },
                        new
                        {
                            Code = "MTR",
                            DecimalPlaces = 3,
                            Name = "Metro",
                            SortOrder = 6
                        },
                        new
                        {
                            Code = "XBX",
                            DecimalPlaces = 0,
                            Name = "Caja",
                            SortOrder = 7
                        },
                        new
                        {
                            Code = "XPK",
                            DecimalPlaces = 0,
                            Name = "Paquete",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("Pos.Domain.Purchases.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LineCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long>("SubtotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("TaxCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VoidedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId", "InvoiceDate")
                        .HasDatabaseName("IX_Purchases_Supplier_InvoiceDate");

                    b.HasIndex("SupplierId", "InvoiceKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Purchases_Supplier_InvoiceKey")
                        .HasFilter("\"Status\" = 'ACTIVE'");

                    b.HasIndex("InvoiceDate", "CreatedAt", "Id")
                        .HasDatabaseName("IX_Purchases_InvoiceDate");

                    b.ToTable("Purchases", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Purchases.PurchaseLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long>("UnitCostCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("VoidMovementId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovementId")
                        .IsUnique()
                        .HasDatabaseName("IX_PurchaseLines_MovementId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_PurchaseLines_ProductId");

                    b.HasIndex("VoidMovementId")
                        .IsUnique()
                        .HasDatabaseName("IX_PurchaseLines_VoidMovementId")
                        .HasFilter("\"VoidMovementId\" IS NOT NULL");

                    b.HasIndex("PurchaseId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_PurchaseLines_Purchase_LineNumber");

                    b.HasIndex("PurchaseId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_PurchaseLines_Purchase_Product");

                    b.ToTable("PurchaseLines", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Receivables.CustomerPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BalanceAfterCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BalanceBeforeCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CashShiftId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VoidAuthorizedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VoidCashShiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VoidedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CashShiftId")
                        .HasDatabaseName("IX_CustomerPayments_CashShiftId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerPayments_Number");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerPayments_RequestId");

                    b.HasIndex("VoidCashShiftId")
                        .HasDatabaseName("IX_CustomerPayments_VoidCashShiftId");

                    b.HasIndex("CustomerId", "CreatedAt")
                        .HasDatabaseName("IX_CustomerPayments_Customer");

                    b.ToTable("CustomerPayments", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Receivables.Receivable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("BalanceCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<long>("OriginalCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OverLimitAuthorizedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaleId")
                        .IsUnique()
                        .HasDatabaseName("IX_Receivables_SaleId");

                    b.HasIndex("CustomerId", "Status", "CreatedAt", "Id")
                        .HasDatabaseName("IX_Receivables_Customer_Status");

                    b.ToTable("Receivables", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Receivables.ReceivableEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerPaymentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceivableId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SaleReturnId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerPaymentId")
                        .HasDatabaseName("IX_ReceivableEntries_Payment");

                    b.HasIndex("ReceivableId", "CreatedAt")
                        .HasDatabaseName("IX_ReceivableEntries_Receivable");

                    b.ToTable("ReceivableEntries", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorizedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CashShiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Compensation")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreditNoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<long>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CashShiftId")
                        .HasDatabaseName("IX_SaleReturns_CashShiftId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("IX_SaleReturns_Number");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("IX_SaleReturns_SaleId");

                    b.ToTable("SaleReturns", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QuantityThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReturnMovementId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleLineId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleReturnId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReturnMovementId");

                    b.HasIndex("SaleLineId")
                        .HasDatabaseName("IX_SaleReturnLines_SaleLine");

                    b.HasIndex("SaleReturnId", "SaleLineId")
                        .IsUnique()
                        .HasDatabaseName("IX_SaleReturnLines_Return_SaleLine");

                    b.ToTable("SaleReturnLines", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturnRefund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReversedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReversedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SalePaymentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleReturnId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SalePaymentId")
                        .HasDatabaseName("IX_SaleReturnRefunds_SalePayment");

                    b.HasIndex("SaleReturnId");

                    b.HasIndex("Status", "Id")
                        .HasDatabaseName("IX_SaleReturnRefunds_Pending")
                        .HasFilter("\"Status\" = 'PENDING_REVERSAL'");

                    b.ToTable("SaleReturnRefunds", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CashShiftId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscountCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<Guid>("DraftId")
                        .HasColumnType("TEXT");

                    b.Property<long>("FolioNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReturnedCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DraftId")
                        .IsUnique()
                        .HasDatabaseName("IX_Sales_DraftId");

                    b.HasIndex("FolioNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Sales_Folio");

                    b.HasIndex("CashShiftId", "Status")
                        .HasDatabaseName("IX_Sales_CashShiftId_Status");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("IX_Sales_CreatedAt");

                    b.HasIndex("CreatedBy", "CreatedAt")
                        .HasDatabaseName("IX_Sales_CreatedBy_CreatedAt");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Sales_Status_CreatedAt");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SaleDiscount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AppliedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorizedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SaleLineId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CouponId")
                        .HasDatabaseName("IX_SaleDiscounts_Coupon");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("IX_SaleDiscounts_Sale");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("IX_SaleDiscounts_CreatedAt");

                    b.ToTable("SaleDiscounts", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SaleDraft", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new Guid("00000000-0000-7000-8000-000000000001"));

                    b.Property<Guid>("DraftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("SaleDrafts", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CancellationMovementId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LineDiscountCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<long>("OrderDiscountCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<long>("OriginalAmountCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReturnedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SaleMovementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long>("UnitPriceCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CancellationMovementId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_SaleLines_Product");

                    b.HasIndex("SaleMovementId");

                    b.HasIndex("SaleId", "Position")
                        .IsUnique()
                        .HasDatabaseName("IX_SaleLines_Sale_Position");

                    b.ToTable("SaleLines", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SalePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChangeCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CreditNoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReceivedCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("SalePayments", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Suppliers.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreditDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("IX_Suppliers_TaxId")
                        .HasFilter("\"TaxId\" IS NOT NULL");

                    b.HasIndex("IsActive", "SearchText")
                        .HasDatabaseName("IX_Suppliers_Active_Search");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEndsAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_NormalizedUserName");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-7000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-7000-8000-000000000001"),
                            FailedLoginCount = 0,
                            FullName = "Sistema",
                            IsActive = false,
                            IsSystem = true,
                            MustChangePassword = false,
                            NormalizedUserName = "SISTEMA",
                            Role = "ADMIN",
                            UpdatedAt = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("00000000-0000-7000-8000-000000000001"),
                            UserName = "Sistema",
                            Version = 1
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Licensing.InstalledLicenseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InstalledLicenses", (string)null);
                });

            modelBuilder.Entity("Pos.Infrastructure.Licensing.LicenseSealEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("LicenseSeals", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Audit.AuditEntry", b =>
                {
                    b.OwnsMany("Pos.Domain.Audit.AuditFieldChange", "Changes", b1 =>
                        {
                            b1.Property<Guid>("AuditEntryId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("After")
                                .HasMaxLength(2000);

                            b1.Property<string>("Before")
                                .HasMaxLength(2000);

                            b1.Property<string>("Field")
                                .IsRequired()
                                .HasMaxLength(80);

                            b1.HasKey("AuditEntryId", "__synthesizedOrdinal");

                            b1.ToTable("AuditEntries");

                            b1
                                .ToJson("Changes")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("AuditEntryId");
                        });

                    b.Navigation("Changes");
                });

            modelBuilder.Entity("Pos.Domain.CashShifts.CashMovement", b =>
                {
                    b.HasOne("Pos.Domain.CashShifts.CashShift", null)
                        .WithMany("Movements")
                        .HasForeignKey("CashShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.CashShifts.ShiftCut", b =>
                {
                    b.HasOne("Pos.Domain.CashShifts.CashShift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.CreditNotes.CreditNote", b =>
                {
                    b.HasOne("Pos.Domain.Returns.SaleReturn", null)
                        .WithMany()
                        .HasForeignKey("SaleReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.CreditNotes.CreditNoteMovement", b =>
                {
                    b.HasOne("Pos.Domain.CreditNotes.CreditNote", null)
                        .WithMany()
                        .HasForeignKey("CreditNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Inventory.InventoryMovement", b =>
                {
                    b.HasOne("Pos.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Inventory.ProductStock", b =>
                {
                    b.HasOne("Pos.Domain.Products.Product", null)
                        .WithOne()
                        .HasForeignKey("Pos.Domain.Inventory.ProductStock", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Products.Product", b =>
                {
                    b.HasOne("Pos.Domain.Products.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("UnitCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Products.ProductImage", b =>
                {
                    b.HasOne("Pos.Domain.Products.Product", null)
                        .WithOne("Image")
                        .HasForeignKey("Pos.Domain.Products.ProductImage", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Purchases.Purchase", b =>
                {
                    b.HasOne("Pos.Domain.Suppliers.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Purchases.PurchaseLine", b =>
                {
                    b.HasOne("Pos.Domain.Inventory.InventoryMovement", null)
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Purchases.Purchase", null)
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Inventory.InventoryMovement", null)
                        .WithMany()
                        .HasForeignKey("VoidMovementId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pos.Domain.Receivables.CustomerPayment", b =>
                {
                    b.HasOne("Pos.Domain.CashShifts.CashShift", null)
                        .WithMany()
                        .HasForeignKey("CashShiftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pos.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.CashShifts.CashShift", null)
                        .WithMany()
                        .HasForeignKey("VoidCashShiftId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pos.Domain.Receivables.Receivable", b =>
                {
                    b.HasOne("Pos.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Sales.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Receivables.ReceivableEntry", b =>
                {
                    b.HasOne("Pos.Domain.Receivables.Receivable", null)
                        .WithMany("Entries")
                        .HasForeignKey("ReceivableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturn", b =>
                {
                    b.HasOne("Pos.Domain.Sales.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturnLine", b =>
                {
                    b.HasOne("Pos.Domain.Inventory.InventoryMovement", null)
                        .WithMany()
                        .HasForeignKey("ReturnMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pos.Domain.Sales.SaleLine", null)
                        .WithMany()
                        .HasForeignKey("SaleLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Returns.SaleReturn", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturnRefund", b =>
                {
                    b.HasOne("Pos.Domain.Sales.SalePayment", null)
                        .WithMany()
                        .HasForeignKey("SalePaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Returns.SaleReturn", null)
                        .WithMany("Refunds")
                        .HasForeignKey("SaleReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Sales.SaleDiscount", b =>
                {
                    b.HasOne("Pos.Domain.Discounts.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pos.Domain.Sales.Sale", null)
                        .WithMany("Discounts")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Sales.SaleLine", b =>
                {
                    b.HasOne("Pos.Domain.Inventory.InventoryMovement", null)
                        .WithMany()
                        .HasForeignKey("CancellationMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pos.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Sales.Sale", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Inventory.InventoryMovement", null)
                        .WithMany()
                        .HasForeignKey("SaleMovementId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SalePayment", b =>
                {
                    b.HasOne("Pos.Domain.Sales.Sale", null)
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.CashShifts.CashShift", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("Pos.Domain.Products.Product", b =>
                {
                    b.Navigation("Image");
                });

            modelBuilder.Entity("Pos.Domain.Purchases.Purchase", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Pos.Domain.Receivables.Receivable", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturn", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Pos.Domain.Sales.Sale", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
