// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.Infrastructure.Persistence;

#nullable disable

namespace Pos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PosDbContext))]
    partial class PosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Pos.Domain.Audit.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditEntries_Entity");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Business.BusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterMessage")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BusinessProfile", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Inventory.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityThousandths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Quantity");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("ResultingStockThousandths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ResultingStock");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("IX_InventoryMovements_CreatedAt");

                    b.HasIndex("ProductId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_InventoryMovements_Product_Sequence");

                    b.HasIndex("Type", "CreatedAt")
                        .HasDatabaseName("IX_InventoryMovements_Type_CreatedAt");

                    b.ToTable("InventoryMovements", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Inventory.ProductStock", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovementCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OnHandThousandths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OnHand");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("ProductStocks", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MinimumStockThousandths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MinimumStock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSearch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PriceCents");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TracksInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("H87");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Barcode")
                        .HasFilter("\"DeletedAt\" IS NULL AND \"Barcode\" IS NOT NULL");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Sku")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("UnitCode");

                    b.HasIndex("NameSearch", "Sku")
                        .HasDatabaseName("IX_Products_NameSearch")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("TracksInventory", "IsActive")
                        .HasDatabaseName("IX_Products_TracksInventory")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Products.ProductImage", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Products.UnitOfMeasure", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("DecimalPlaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("UnitsOfMeasure", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "H87",
                            DecimalPlaces = 0,
                            Name = "Pieza",
                            SortOrder = 1
                        },
                        new
                        {
                            Code = "KGM",
                            DecimalPlaces = 3,
                            Name = "Kilogramo",
                            SortOrder = 2
                        },
                        new
                        {
                            Code = "GRM",
                            DecimalPlaces = 0,
                            Name = "Gramo",
                            SortOrder = 3
                        },
                        new
                        {
                            Code = "LTR",
                            DecimalPlaces = 3,
                            Name = "Litro",
                            SortOrder = 4
                        },
                        new
                        {
                            Code = "MLT",
                            DecimalPlaces = 0,
                            Name = "Mililitro",
                            SortOrder = 5
                        },
                        new
                        {
                            Code = "MTR",
                            DecimalPlaces = 3,
                            Name = "Metro",
                            SortOrder = 6
                        },
                        new
                        {
                            Code = "XBX",
                            DecimalPlaces = 0,
                            Name = "Caja",
                            SortOrder = 7
                        },
                        new
                        {
                            Code = "XPK",
                            DecimalPlaces = 0,
                            Name = "Paquete",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("Pos.Domain.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("TEXT");

                    b.Property<long>("FolioNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DraftId")
                        .IsUnique()
                        .HasDatabaseName("IX_Sales_DraftId");

                    b.HasIndex("FolioNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Sales_Folio");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("IX_Sales_CreatedAt");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Sales_Status_CreatedAt");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SaleDraft", b =>
                {
                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Slot");

                    b.ToTable("SaleDrafts", null, t =>
                        {
                            t.HasCheckConstraint("CK_SaleDrafts_Slot", "\"Slot\" = 1");
                        });
                });

            modelBuilder.Entity("Pos.Domain.Sales.SaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CancellationMovementId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SaleMovementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long>("UnitPriceCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CancellationMovementId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_SaleLines_Product");

                    b.HasIndex("SaleMovementId");

                    b.HasIndex("SaleId", "Position")
                        .IsUnique()
                        .HasDatabaseName("IX_SaleLines_Sale_Position");

                    b.ToTable("SaleLines", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SalePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChangeCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReceivedCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("SalePayments", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Inventory.InventoryMovement", b =>
                {
                    b.HasOne("Pos.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Inventory.ProductStock", b =>
                {
                    b.HasOne("Pos.Domain.Products.Product", null)
                        .WithOne()
                        .HasForeignKey("Pos.Domain.Inventory.ProductStock", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Products.Product", b =>
                {
                    b.HasOne("Pos.Domain.Products.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("UnitCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Products.ProductImage", b =>
                {
                    b.HasOne("Pos.Domain.Products.Product", null)
                        .WithOne("Image")
                        .HasForeignKey("Pos.Domain.Products.ProductImage", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Sales.SaleLine", b =>
                {
                    b.HasOne("Pos.Domain.Inventory.InventoryMovement", null)
                        .WithMany()
                        .HasForeignKey("CancellationMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pos.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Sales.Sale", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Inventory.InventoryMovement", null)
                        .WithMany()
                        .HasForeignKey("SaleMovementId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SalePayment", b =>
                {
                    b.HasOne("Pos.Domain.Sales.Sale", null)
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Products.Product", b =>
                {
                    b.Navigation("Image");
                });

            modelBuilder.Entity("Pos.Domain.Sales.Sale", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
