// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.Infrastructure.Persistence;

#nullable disable

namespace Pos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PosDbContext))]
    partial class PosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Pos.Domain.Audit.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorizedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditEntries_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_AuditEntries_CreatedBy");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditEntries_Entity");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Business.BusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterMessage")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BusinessProfile", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.CashShifts.CashMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AuthorizedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CashShiftId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CashShiftId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_CashMovements_Shift_Sequence");

                    b.ToTable("CashMovements", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.CashShifts.CashShift", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CancelledCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CardCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CashCancelledCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CashRefundsCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CashSalesCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosingComment")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CountedCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreditNotesIssuedCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DepositsCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DifferenceCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExpectedCashCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NonCashRefundsCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OpenedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpeningFloatCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegisterCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SalesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TotalSoldCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TransferCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("WithdrawalsCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("IX_CashShifts_Number");

                    b.HasIndex("RegisterCode")
                        .IsUnique()
                        .HasDatabaseName("IX_CashShifts_OpenPerRegister")
                        .HasFilter("\"Status\" = 'OPEN'");

                    b.HasIndex("OpenedAt", "Id")
                        .HasDatabaseName("IX_CashShifts_OpenedAt");

                    b.HasIndex("OpenedBy", "OpenedAt")
                        .HasDatabaseName("IX_CashShifts_OpenedBy_OpenedAt");

                    b.ToTable("CashShifts", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.CreditNotes.CreditNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("InitialCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SaleReturnId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("IX_CreditNotes_Number");

                    b.HasIndex("SaleReturnId")
                        .HasDatabaseName("IX_CreditNotes_SaleReturnId");

                    b.ToTable("CreditNotes", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.CreditNotes.CreditNoteMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreditNoteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SaleReturnId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreditNoteId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_CreditNoteMovements_Note_Sequence");

                    b.ToTable("CreditNoteMovements", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Inventory.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityThousandths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Quantity");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("ResultingStockThousandths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ResultingStock");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("IX_InventoryMovements_CreatedAt");

                    b.HasIndex("ProductId", "CreatedAt")
                        .HasDatabaseName("IX_InventoryMovements_Product_CreatedAt");

                    b.HasIndex("ProductId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_InventoryMovements_Product_Sequence");

                    b.HasIndex("Type", "CreatedAt")
                        .HasDatabaseName("IX_InventoryMovements_Type_CreatedAt");

                    b.ToTable("InventoryMovements", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Inventory.ProductStock", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovementCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OnHandThousandths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OnHand");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("ProductStocks", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCritical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<long?>("MinimumStockThousandths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MinimumStock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSearch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PriceCents");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TracksInventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("H87");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Barcode")
                        .HasFilter("\"DeletedAt\" IS NULL AND \"Barcode\" IS NOT NULL");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Sku")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("UnitCode");

                    b.HasIndex("NameSearch", "Sku")
                        .HasDatabaseName("IX_Products_NameSearch")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("TracksInventory", "IsActive")
                        .HasDatabaseName("IX_Products_TracksInventory")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Products.ProductImage", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Products.UnitOfMeasure", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("DecimalPlaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("UnitsOfMeasure", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "H87",
                            DecimalPlaces = 0,
                            Name = "Pieza",
                            SortOrder = 1
                        },
                        new
                        {
                            Code = "KGM",
                            DecimalPlaces = 3,
                            Name = "Kilogramo",
                            SortOrder = 2
                        },
                        new
                        {
                            Code = "GRM",
                            DecimalPlaces = 0,
                            Name = "Gramo",
                            SortOrder = 3
                        },
                        new
                        {
                            Code = "LTR",
                            DecimalPlaces = 3,
                            Name = "Litro",
                            SortOrder = 4
                        },
                        new
                        {
                            Code = "MLT",
                            DecimalPlaces = 0,
                            Name = "Mililitro",
                            SortOrder = 5
                        },
                        new
                        {
                            Code = "MTR",
                            DecimalPlaces = 3,
                            Name = "Metro",
                            SortOrder = 6
                        },
                        new
                        {
                            Code = "XBX",
                            DecimalPlaces = 0,
                            Name = "Caja",
                            SortOrder = 7
                        },
                        new
                        {
                            Code = "XPK",
                            DecimalPlaces = 0,
                            Name = "Paquete",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorizedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CashShiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Compensation")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreditNoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<long>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CashShiftId")
                        .HasDatabaseName("IX_SaleReturns_CashShiftId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("IX_SaleReturns_Number");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("IX_SaleReturns_SaleId");

                    b.ToTable("SaleReturns", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QuantityThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReturnMovementId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleLineId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleReturnId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReturnMovementId");

                    b.HasIndex("SaleLineId")
                        .HasDatabaseName("IX_SaleReturnLines_SaleLine");

                    b.HasIndex("SaleReturnId", "SaleLineId")
                        .IsUnique()
                        .HasDatabaseName("IX_SaleReturnLines_Return_SaleLine");

                    b.ToTable("SaleReturnLines", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturnRefund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReversedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReversedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SalePaymentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleReturnId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SalePaymentId")
                        .HasDatabaseName("IX_SaleReturnRefunds_SalePayment");

                    b.HasIndex("SaleReturnId");

                    b.HasIndex("Status", "Id")
                        .HasDatabaseName("IX_SaleReturnRefunds_Pending")
                        .HasFilter("\"Status\" = 'PENDING_REVERSAL'");

                    b.ToTable("SaleReturnRefunds", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CashShiftId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("TEXT");

                    b.Property<long>("FolioNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReturnedCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DraftId")
                        .IsUnique()
                        .HasDatabaseName("IX_Sales_DraftId");

                    b.HasIndex("FolioNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Sales_Folio");

                    b.HasIndex("CashShiftId", "Status")
                        .HasDatabaseName("IX_Sales_CashShiftId_Status");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("IX_Sales_CreatedAt");

                    b.HasIndex("CreatedBy", "CreatedAt")
                        .HasDatabaseName("IX_Sales_CreatedBy_CreatedAt");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Sales_Status_CreatedAt");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SaleDraft", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new Guid("00000000-0000-7000-8000-000000000001"));

                    b.Property<Guid>("DraftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("SaleDrafts", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CancellationMovementId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("QuantityThousandths")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReturnedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SaleMovementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long>("UnitPriceCents")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CancellationMovementId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_SaleLines_Product");

                    b.HasIndex("SaleMovementId");

                    b.HasIndex("SaleId", "Position")
                        .IsUnique()
                        .HasDatabaseName("IX_SaleLines_Sale_Position");

                    b.ToTable("SaleLines", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SalePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChangeCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CreditNoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReceivedCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("SalePayments", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEndsAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_NormalizedUserName");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-7000-8000-000000000001"),
                            CreatedAt = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("00000000-0000-7000-8000-000000000001"),
                            FailedLoginCount = 0,
                            FullName = "Sistema",
                            IsActive = false,
                            IsSystem = true,
                            MustChangePassword = false,
                            NormalizedUserName = "SISTEMA",
                            Role = "ADMIN",
                            UpdatedAt = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("00000000-0000-7000-8000-000000000001"),
                            UserName = "Sistema",
                            Version = 1
                        });
                });

            modelBuilder.Entity("Pos.Infrastructure.Licensing.LicenseSealEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("LicenseSeals", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.CashShifts.CashMovement", b =>
                {
                    b.HasOne("Pos.Domain.CashShifts.CashShift", null)
                        .WithMany("Movements")
                        .HasForeignKey("CashShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.CreditNotes.CreditNote", b =>
                {
                    b.HasOne("Pos.Domain.Returns.SaleReturn", null)
                        .WithMany()
                        .HasForeignKey("SaleReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.CreditNotes.CreditNoteMovement", b =>
                {
                    b.HasOne("Pos.Domain.CreditNotes.CreditNote", null)
                        .WithMany()
                        .HasForeignKey("CreditNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Inventory.InventoryMovement", b =>
                {
                    b.HasOne("Pos.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Inventory.ProductStock", b =>
                {
                    b.HasOne("Pos.Domain.Products.Product", null)
                        .WithOne()
                        .HasForeignKey("Pos.Domain.Inventory.ProductStock", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Products.Product", b =>
                {
                    b.HasOne("Pos.Domain.Products.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("UnitCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Products.ProductImage", b =>
                {
                    b.HasOne("Pos.Domain.Products.Product", null)
                        .WithOne("Image")
                        .HasForeignKey("Pos.Domain.Products.ProductImage", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturn", b =>
                {
                    b.HasOne("Pos.Domain.Sales.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturnLine", b =>
                {
                    b.HasOne("Pos.Domain.Inventory.InventoryMovement", null)
                        .WithMany()
                        .HasForeignKey("ReturnMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pos.Domain.Sales.SaleLine", null)
                        .WithMany()
                        .HasForeignKey("SaleLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Returns.SaleReturn", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturnRefund", b =>
                {
                    b.HasOne("Pos.Domain.Sales.SalePayment", null)
                        .WithMany()
                        .HasForeignKey("SalePaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Returns.SaleReturn", null)
                        .WithMany("Refunds")
                        .HasForeignKey("SaleReturnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.Sales.SaleLine", b =>
                {
                    b.HasOne("Pos.Domain.Inventory.InventoryMovement", null)
                        .WithMany()
                        .HasForeignKey("CancellationMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pos.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Sales.Sale", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pos.Domain.Inventory.InventoryMovement", null)
                        .WithMany()
                        .HasForeignKey("SaleMovementId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Pos.Domain.Sales.SalePayment", b =>
                {
                    b.HasOne("Pos.Domain.Sales.Sale", null)
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pos.Domain.CashShifts.CashShift", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("Pos.Domain.Products.Product", b =>
                {
                    b.Navigation("Image");
                });

            modelBuilder.Entity("Pos.Domain.Returns.SaleReturn", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Pos.Domain.Sales.Sale", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
